// Code generated by command: go run gen.go -out ../scan_amd64.s -pkg jsonx. DO NOT EDIT.

#include "textflag.h"

// func scanStringSIMD(p *byte, n int) int
// Requires: AVX, AVX512BW, AVX512F, BMI
TEXT ·scanStringSIMD(SB), NOSPLIT, $0-24
	MOVQ         p+0(FP), AX
	MOVQ         n+8(FP), CX
	XORQ         DX, DX
	MOVQ         $0x00000022, BX
	VPBROADCASTB BX, Z0
	MOVQ         $0x0000005c, BX
	VPBROADCASTB BX, Z1
	MOVQ         $0x00000020, BX
	VPBROADCASTB BX, Z2
	MOVQ         $0x0000003c, BX
	VPBROADCASTB BX, Z3
	MOVQ         $0x0000003e, BX
	VPBROADCASTB BX, Z4
	MOVQ         $0x00000026, BX
	VPBROADCASTB BX, Z5
	MOVQ         $0x00000080, BX
	VPBROADCASTB BX, Z6

loop:
	MOVQ      CX, BX
	SUBQ      DX, BX
	CMPQ      BX, $0x00000040
	JL        tail
	VMOVDQU64 (AX)(DX*1), Z7
	VPCMPEQB  Z0, Z7, K1
	VPCMPEQB  Z1, Z7, K2
	KORQ      K1, K2, K1
	VPCMPUB   $0x01, Z2, Z7, K2
	KORQ      K1, K2, K1
	VPCMPEQB  Z3, Z7, K2
	KORQ      K1, K2, K1
	VPCMPEQB  Z4, Z7, K2
	KORQ      K1, K2, K1
	VPCMPEQB  Z5, Z7, K2
	KORQ      K1, K2, K1
	VPCMPUB   $0x05, Z6, Z7, K2
	KORQ      K1, K2, K1
	KTESTQ    K1, K1
	JNZ       found64
	ADDQ      $0x00000040, DX
	JMP       loop

found64:
	KMOVQ  K1, AX
	TZCNTQ AX, AX
	ADDQ   AX, DX
	MOVQ   DX, ret+16(FP)
	VZEROUPPER
	RET

tail:
tail_loop:
	CMPQ DX, CX
	JGE  notfound
	MOVB (AX)(DX*1), BL
	CMPB BL, $0x22
	JE   done
	CMPB BL, $0x5c
	JE   done
	CMPB BL, $0x20
	JB   done
	CMPB BL, $0x3c
	JE   done
	CMPB BL, $0x3e
	JE   done
	CMPB BL, $0x26
	JE   done
	CMPB BL, $0x80
	JAE  done
	INCQ DX
	JMP  tail_loop

notfound:
done:
	MOVQ DX, ret+16(FP)
	VZEROUPPER
	RET
